#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@yaml/text-templated-strings
---
apiVersion: v1
data:
  watched_registry_password: (@= base64.encode(str(data.values.buildpack_labels_operator.watched_registry_password)) @)
  watched_registry_username: (@= base64.encode(str(data.values.buildpack_labels_operator.watched_registry_username)) @)
kind: Secret
metadata:
  name: buildpack-labels-operator-operator-secret
  namespace: buildpack-labels-operator-system
type: Opaque