apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: buildpack-labels-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: buildpack-labels-operator-controller-manager
  namespace: buildpack-labels-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildpack-labels-operator-leader-election-role
  namespace: buildpack-labels-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: buildpack-labels-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildpack-labels-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: buildpack-labels-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildpack-labels-operator-leader-election-rolebinding
  namespace: buildpack-labels-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildpack-labels-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: buildpack-labels-operator-controller-manager
  namespace: buildpack-labels-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildpack-labels-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buildpack-labels-operator-manager-role
subjects:
- kind: ServiceAccount
  name: buildpack-labels-operator-controller-manager
  namespace: buildpack-labels-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: buildpack-labels-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: buildpack-labels-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: buildpack-labels-operator-controller-manager
  namespace: buildpack-labels-operator-system
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: d03718e9.moussaud.org
kind: ConfigMap
metadata:
  name: buildpack-labels-operator-manager-config
  namespace: buildpack-labels-operator-system
---
apiVersion: v1
data:
  PREFIX_IMAGE_LABEL: watermark.
  PREFIX_POD_LABEL: app.map
  REQUEST_DEBUG: "false"
  WATCHED_REGISTRY: harbor.mytanzu.xyz
kind: ConfigMap
metadata:
  name: buildpack-labels-operator-operator-config
  namespace: buildpack-labels-operator-system
---
apiVersion: v1
data:
  watched_registry_password: MzkxQkdJa3FaeHYwS3M3OGJhaVp4OVJ0dENrNGNpVTY=
  watched_registry_username: cm9ib3QkYnVpbGRwYWNrLWxhYmVscy1vcGVyYXRvcg==
kind: Secret
metadata:
  name: buildpack-labels-operator-operator-secret
  namespace: buildpack-labels-operator-system
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: buildpack-labels-operator-controller-manager-metrics-service
  namespace: buildpack-labels-operator-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: buildpack-labels-operator-controller-manager
  namespace: buildpack-labels-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: WATCHED_REGISTRY
          valueFrom:
            configMapKeyRef:
              key: WATCHED_REGISTRY
              name: buildpack-labels-operator-operator-config
        - name: PREFIX_IMAGE_LABEL
          valueFrom:
            configMapKeyRef:
              key: PREFIX_IMAGE_LABEL
              name: buildpack-labels-operator-operator-config
        - name: REQUEST_DEBUG
          valueFrom:
            configMapKeyRef:
              key: REQUEST_DEBUG
              name: buildpack-labels-operator-operator-config
        - name: PREFIX_POD_LABEL
          valueFrom:
            configMapKeyRef:
              key: PREFIX_POD_LABEL
              name: buildpack-labels-operator-operator-config
        - name: WATCHED_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              key: watched_registry_username
              name: buildpack-labels-operator-operator-secret
        - name: WATCHED_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              key: watched_registry_password
              name: buildpack-labels-operator-operator-secret
        image: ghcr.io/bmoussaud/buildpack-labels-operator:0.0.2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: buildpack-labels-operator-controller-manager
      terminationGracePeriodSeconds: 10
