---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.8.0
          url: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
      - preresolved:
          url: gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
      - preresolved:
          url: gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
      - preresolved:
          url: gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
  image: gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
- annotations:
    kbld.carvel.dev/id: ghcr.io/bmoussaud/buildpack-labels-operator:v0.0.1
    kbld.carvel.dev/origins: |
      - resolved:
          tag: v0.0.1
          url: ghcr.io/bmoussaud/buildpack-labels-operator:v0.0.1
      - preresolved:
          url: ghcr.io/bmoussaud/buildpack-labels-operator@sha256:49333d38aed8829428fe5c508054e349f2ad772ff5392ed38a603a2ff4a6e567
      - preresolved:
          url: ghcr.io/bmoussaud/buildpack-labels-operator@sha256:49333d38aed8829428fe5c508054e349f2ad772ff5392ed38a603a2ff4a6e567
      - preresolved:
          url: ghcr.io/bmoussaud/buildpack-labels-operator@sha256:49333d38aed8829428fe5c508054e349f2ad772ff5392ed38a603a2ff4a6e567
  image: ghcr.io/bmoussaud/buildpack-labels-operator@sha256:49333d38aed8829428fe5c508054e349f2ad772ff5392ed38a603a2ff4a6e567
kind: ImagesLock
